### ISSUE TITLE
TeX display is broken in online documentation

### ISSUE THREAD

**Issue by stillyslalom** [ranocha/BSeries.jl#83]
Mostly on this page: https://ranocha.de/BSeries.jl/v0.1/tutorials/bseries_basics/#Exact-series-and-local-error
![image](https://user-images.githubusercontent.com/4324760/193863177-336b4e50-1ceb-4226-a332-cd13b86be021.png)

**Comment by ranocha** [comment]
The problem with these parts is mentioned a bit earlier on the same page: 

> The rooted trees written in this way can be rendered in LaTeX using the package [forest](https://ctan.org/pkg/forest); unfortunately, there is no easy way to render them in the browser.

The problem is that we would need to be able to load the LaTeX package [forest](https://ctan.org/pkg/forest) based on PGF/TikZ to render the `\rootedtree` macros. 

The default backend of Documenter.jl is KaTeX, but I could not find a way to load packages for it (on https://katex.org/docs/options.html, https://github.com/KaTeX/KaTeX/issues/1749, https://github.com/KaTeX/KaTeX/issues/793).  

The same holds for the MathJax backends (e.g., https://stackoverflow.com/questions/21192606/can-i-add-latex-packages-to-mathjax). 

I would be happy to fix the rendering of these equations, but I sadly have no idea how to achieve that. Do you have an idea, @stillyslalom?

**Comment by stillyslalom** [comment]
I missed that disclaimer, sorry! The most robust way seems to be using PGF/TikZ to generate SVG files as part of the documentation rendering pipeline, but I agree that there's no way to do it with MathJax or KaTeX. Maybe with [TikzGraphs.jl](https://nbviewer.org/github/JuliaTeX/TikzGraphs.jl/blob/master/doc/TikzGraphs.ipynb) or just using the built-in `display` methods from one of the other [graph visualization packages](https://juliagraphs.org/Graphs.jl/dev/first_steps/plotting/)?

**Comment by ranocha** [comment]
That may be an idea but looks quite complicated to me. The problem is that we rely on a LaTeX package to draw the trees and combine this in an equation with other stuff in LaTeX. Maybe it would be okay to just generate the output from LaTeX locally and upload it (or execute LaTeX while running CI).

**Comment by stillyslalom** [comment]
My wording was unclear, but I meant to mention two separate ideas: rendering with TikZ during docs build on CI (probably challenging), or using something like [GraphMakie.jl](https://graph.makie.org/stable/generated/syntaxtree/) and [MathTeXEngine.jl](https://github.com/Kolaru/MathTeXEngine.jl/) to draw the trees instead of using a LaTeX-based pipeline.

**Comment by ranocha** [comment]
For reference, the output of the five equations on the page you linked should look as follows.

1:
![bseries_creation_eq1-1](https://user-images.githubusercontent.com/12693098/193994163-e53d24a8-f74e-4f95-b07d-225ebde83f70.png)

2:
![bseries_creation_eq2-1](https://user-images.githubusercontent.com/12693098/193994166-a9178001-702d-4f9b-a3f6-6a89251ddb7f.png)

3:
![bseries_creation_eq3-1](https://user-images.githubusercontent.com/12693098/193994175-22356d01-edb9-44b6-afd3-4354a3daffc6.png)

4:
![bseries_creation_eq4-1](https://user-images.githubusercontent.com/12693098/193994179-7ffcced2-6760-46fc-829a-d6c5814d543f.png)

5:
![bseries_creation_eq5-1](https://user-images.githubusercontent.com/12693098/193994181-108aa3a7-e2fb-4247-a770-9647ebe861c8.png)

**Comment by ranocha** [comment]
I added the pre-rendered equations in #84. If someone finds the time, it might be nice to automate the rendering via GitHub actions, but the introduction should be stable enough for now ("perfect is the enemy of good").
